### ISSUE TITLE
no fonts affect Square root 

### ISSUE THREAD

**Issue by emrekocyatagi** [rototor/jeuclid#10] opened 2022-07-13 15:07 UTC
Hey,
I am converting equation from mathml to svg.
`mml2xxx equation1.mml deneme5.svg -fontSize 100.0 -fontsSerif "cambria math"`
The equation is square root of pi.
This cambria math font only affect the pi,  I mean pi's font is changing but square no.
in cambria math font square root is like this.....
![image](https://user-images.githubusercontent.com/88593075/178767843-08496da4-b3ba-4ca3-b0da-5ea7a3e66ebf.png)
And the problem is these corner is broken and not same
![nYqnSoPVE2eXzEPV](https://user-images.githubusercontent.com/88593075/178768111-502bf7bd-1862-4d0e-a2a5-d72c8577dc12.png)

You can see the equation with different fontstyle.
Could please help me to get correct output?
![calibri](https://user-images.githubusercontent.com/88593075/178767076-fb05a45b-a2cd-4be2-88d0-abede65cc81a.svg)
![cambria](https://user-images.githubusercontent.com/88593075/178767079-54150a24-512c-4590-88b2-d8c2f20743b6.svg)
![cambria-math](https://user-images.githubusercontent.com/88593075/178767084-461531f1-b97b-47cb-a501-5d5b115ce929.svg)
![candara](https://user-images.githubusercontent.com/88593075/178767086-32967319-79cb-4939-87ad-0714631555f3.svg)
![castellar](https://user-images.githubusercontent.com/88593075/178767088-e9ff0303-6155-4db3-8501-504f7734c339.svg)
![centaur](https://user-images.githubusercontent.com/88593075/178767090-185eeee1-6f92-4e99-92d0-e80968961de2.svg)
![dubai](https://user-images.githubusercontent.com/88593075/178767092-1b4fa452-d925-4302-b7f3-8eab500c95b7.svg)
![ebrima](https://user-images.githubusercontent.com/88593075/178767095-bf4c5a6c-dea1-4cf6-a511-38da9471245d.svg)
![eufm10](https://user-images.githubusercontent.com/88593075/178767096-5f5cd685-2825-4842-b59b-26d3bb949ebe.svg)
![arial](https://user-images.githubusercontent.com/88593075/178767099-e9e50f79-16c9-47e8-9a75-33ef0a5fd237.svg)

**Comment by rototor** [comment] 2022-07-13 15:45
@umutyoldaa Sorry, but I really can't help you here. i only got it working with JDK 11 to integrate it into openhtmltopdf. 
I know exactly as much about the inner working of this library as you do (Nothing...). So you have to debug this problem yourself.

If you can make a pull request with a fix for this, I'm happy to integrate it and release a new version.

**Comment by emrekocyatagi** [comment] 2022-07-14 06:52
Okay,
I check the most of conventor (online/cli/java/javascript) most of them has same problem.
But thanks anyway.

**Comment by rototor** [comment] 2022-07-14 07:52
Well, the problem is that the square root is rendered using three distinct lines:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/711674/178930784-82799287-da5d-486c-800b-1447f80ec7ce.png">

If this would just be one single path, you would not get this edge artefacts.

**Comment by rototor** [comment] 2022-07-14 11:12
Just out of curiosity I looked into this: The root is generated here:

https://github.com/rototor/jeuclid/blob/master/jeuclid-core/src/main/java/net/sourceforge/jeuclid/elements/presentation/general/AbstractRoot.java#L142

Instead of a line object it would be needed to make some new kind of PathObject and add all those single lines to it. If it is exported as path, the resulting path will have the edges as defined by the Line Joins style. 

@umutyoldaa Can you provide me this sample file? Thanks.

**Comment by emrekocyatagi** [comment] 2022-07-14 11:55
`<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" stroke-dasharray="none" shape-rendering="auto" font-family="'Dialog'" width="16" text-rendering="auto" fill-opacity="1" contentScriptType="text/ecmascript" color-interpolation="auto" color-rendering="auto" preserveAspectRatio="xMidYMid meet" font-size="12" fill="black" stroke="black" image-rendering="auto" stroke-miterlimit="10" zoomAndPan="magnify" version="1.0" stroke-linecap="square" stroke-linejoin="miter" contentStyleType="text/css" font-style="normal" height="19" stroke-width="1" stroke-dashoffset="0" font-weight="normal" stroke-opacity="1"><!--Converted from MathML using JEuclid--><defs id="genericDefs"/><g><g text-rendering="optimizeLegibility" color-rendering="optimizeQuality" color-interpolation="linearRGB" image-rendering="optimizeQuality"><line y2="18" fill="none" x1="1" x2="3.5167" y1="10.44"/><line y2="1.3" fill="none" x1="3.5167" x2="6.0333" y1="18"/><line y2="1.3" fill="none" x1="6.0333" x2="14.1708" y1="1.3"/><path d="M1.6875 -4.8125 Q1.2656 -4.8125 1.0078 -4.6797 Q0.75 -4.5469 0.4375 -4.1406 L0.0781 -4.4531 Q0.5781 -5.1562 0.9609 -5.3828 Q1.3438 -5.6094 2 -5.6094 L6.9375 -5.6094 L6.9375 -4.8125 L5.5156 -4.8125 L5.5156 -1.2969 Q5.5156 -0.5312 5.9531 -0.5312 Q6.2031 -0.5312 6.5625 -0.8281 L6.7812 -0.4688 Q6.125 0.0938 5.5156 0.0938 Q5 0.0938 4.75 -0.25 Q4.5 -0.5938 4.5 -1.3906 L4.5 -4.8125 L2.7031 -4.8125 L2.7031 0 L1.5312 0 L1.5312 -0.2812 Q1.8906 -1.6719 1.8906 -4 L1.8906 -4.8125 L1.6875 -4.8125 Z" transform="translate(6.0333,15)" stroke="none"/></g></g></svg>`
this is my sample svg
I am not expert in this field. I can understand  you but actually I have no idea what to do. Do you want me to send  `AbstractRoot.java`?
![equation (5)](https://user-images.githubusercontent.com/88593075/178976031-f81556ed-675d-4487-861c-9c4971477940.svg)
`
<path d='M4.65056 10.2217L2.54645 5.57111C2.46276 5.37983 2.40299 5.37983 2.36712 5.37983C2.35517 5.37983 2.29539 5.37983 2.16389 5.47547L1.02814 6.33624C0.872727 6.45579 0.872727 6.49166 0.872727 6.52752C0.872727 6.5873 0.908593 6.65903 0.992279 6.65903C1.06401 6.65903 1.26725 6.49166 1.39875 6.39601C1.47049 6.33624 1.64981 6.20473 1.78132 6.10909L4.13649 11.2857C4.22017 11.477 4.27995 11.477 4.38755 11.477C4.56687 11.477 4.60274 11.4052 4.68643 11.2379L10.1141 0C10.1978 -0.167372 10.1978 -0.215193 10.1978 -0.239103C10.1978 -0.358655 10.1021 -0.478207 9.95866 -0.478207C9.86301 -0.478207 9.77933 -0.418431 9.68369 -0.227148L4.65056 10.2217Z' id='g0-112'/> `
`<path d='M3.09639 -4.5071H4.44732C4.12453 -3.16812 3.9213 -2.29539 3.9213 -1.33898C3.9213 -1.17161 3.9213 0.119552 4.41146 0.119552C4.66252 0.119552 4.87771 -0.107597 4.87771 -0.310834C4.87771 -0.37061 4.87771 -0.394521 4.79402 -0.573848C4.47123 -1.39875 4.47123 -2.4269 4.47123 -2.51059C4.47123 -2.58232 4.47123 -3.43113 4.72229 -4.5071H6.06127C6.21669 -4.5071 6.61121 -4.5071 6.61121 -4.88966C6.61121 -5.15268 6.38406 -5.15268 6.16887 -5.15268H2.23562C1.96065 -5.15268 1.55417 -5.15268 1.00423 -4.56687C0.6934 -4.22017 0.310834 -3.58655 0.310834 -3.51482S0.37061 -3.41918 0.442341 -3.41918C0.526027 -3.41918 0.537983 -3.45504 0.597758 -3.52677C1.21943 -4.5071 1.8411 -4.5071 2.13998 -4.5071H2.82142C2.55841 -3.61046 2.25953 -2.57036 1.2792 -0.478207C1.18356 -0.286924 1.18356 -0.263014 1.18356 -0.191283C1.18356 0.0597758 1.39875 0.119552 1.50635 0.119552C1.85305 0.119552 1.94869 -0.191283 2.09215 -0.6934C2.28344 -1.30311 2.28344 -1.32702 2.40299 -1.80523L3.09639 -4.5071Z' id='g1-25'/> `


I got this svg from https://latex2image.joeraut.com/
and as you can see there is no `<line>` there are only 2 `<path>`
And thank you so much for your cruise :)

**Comment by rototor** [comment] 2022-07-14 15:56
Sorry, I meant that you should send me the equation1.mml file.

**Comment by emrekocyatagi** [comment] 2022-07-14 16:08
`<math> <msqrt mathvariant='italic'> <mi mathvariant='normal'>π</mi></msqrt> </math> `
Sorry here dosen't support mml file. this is what i have inside the equation1.mml

**Comment by rototor** [comment] 2022-07-14 18:54
I can offer you this two versions: 
![test2](https://user-images.githubusercontent.com/711674/179059500-f4a040b1-6302-4756-93b7-9b2cd4d578d7.svg)
![test3](https://user-images.githubusercontent.com/711674/179059503-c8c748dc-3689-4fae-80aa-2dde06251130.svg)

This looks both a bit better, but more styling is only possible by hardcoding that styles. See 1436b09

As - for whatever reason - the jeuclid testsuite is bailing out about something not being correctly layouted, I can not deploy that to maven central at the moment. So the only way to use this is to grab the sources and build this for yourself.

**Closed as completed by rototor** 2022-07-14 18:54 UTC
